decrease node instances and increase relays
input-output-hk/cardano-ops pull request #406
Opened 2022-09-19 03:48 UTC by craigem

Relays have maxed out RAM available to `t3.2xlarge` instance types.

This PR reduces the number of node instances per relay from 3 to 2.

It compensates for this instance reduction by increasing `minRelays` relatively.

2022-09-20 09:38 UTC, jbgi requested changes

2022-09-20 09:38 UTC, jbgi commented on topologies/mainnet.nix
> +      minRelays = 52;
Thinking to leave `minRelays` as is for now, and instead increase `-N` to match number of cores available per instance.
Adding a commit implementing this.

2022-09-20 19:30 UTC, jbgi approved these changes

2022-09-21 00:41 UTC, craigem commented on globals-mainnet.nix
> +  nbInstancesPerRelay = 2;
Thanks JB :smile:

2022-09-21 00:43 UTC, merged